name: sync.yaml

on:
  push:
    branches: ["main"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EC2_METADATA_DISABLED: "true" # https://github.com/aws/aws-cli/issues/5262


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint
          cfn-lint --version

      - name: Lint the cloudformation template
        run: |
          cfn-lint -t ./**/*.yaml

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - uses: actions/checkout@v4

      - name: Sync the changes to S3 bucket
        run: |
          aws s3 sync . s3://cfn-stack-template-storage \
            --exclude '.github/*' \
            --exclude '.git/*' \
            --exclude 'README.md'
